# For public, HTTPS servers.
version: '2.2'

services:
  postgres:
    image: mdillon/postgis:9.5
    hostname: postgres
    env_file:
      - ../kobo-deployments/envfile.txt
      - ../kobo-deployments/envfiles/databases.txt
      - ../kobo-deployments/envfiles/aws.txt
    volumes:
      - ./.vols/db:/var/lib/postgresql/data
      - ./backups/postgres:/srv/backups
      - ./log/postgres:/srv/logs
      - ./postgres:/kobo-docker-scripts
    command: "/bin/bash /kobo-docker-scripts/entrypoint.sh"
    restart: on-failure

  mongo:
    image: mongo:3.4
    hostname: mongo
    environment:
      - MONGO_DATA=/data/db
    env_file:
      - ../kobo-deployments/envfile.txt
      - ../kobo-deployments/envfiles/databases.txt
      - ../kobo-deployments/envfiles/aws.txt
    volumes:
      - ./.vols/mongo:/data/db
      - ./backups/mongo:/srv/backups
      - ./mongo:/kobo-docker-scripts
      - ./log/mongo:/srv/logs
    restart: on-failure
    command: "/bin/bash /kobo-docker-scripts/entrypoint.sh"

  redis_main:
    image: redis:3.2
    env_file:
      - ../kobo-deployments/envfile.txt
      - ../kobo-deployments/envfiles/databases.txt
      - ../kobo-deployments/envfiles/aws.txt
    volumes:
      - ./redis:/kobo-docker-scripts
      - ./backups/redis:/srv/backups
      - ./.vols/redis_main_data/:/data/
      - ./redis/redis-enketo-main.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_main:/var/log/redis
    restart: on-failure
    sysctls:
        - net.core.somaxconn=2048
    command: "/bin/bash /tmp/redis/entrypoint.sh"

  redis_cache:
    image: redis:3.2
    env_file:
      - ../kobo-deployments/envfiles/databases.txt
    volumes:
      - ./.vols/redis_cache_data/:/data/
      - ./redis/redis-enketo-cache.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_cache:/var/log/redis
    restart: on-failure
    sysctls:
        - net.core.somaxconn=2048
    command: "/bin/bash /tmp/redis/entrypoint.sh"
