# For public, HTTPS servers.

rabbit:
  image: kobotoolbox/rabbit:latest
  # Dev: Build the image locally.
  # build: ./base_images/rabbit
  hostname: rabbit
  environment:
    - RABBITMQ_LOG_BASE=/var/log/rabbitmq
  volumes:
    - ./log/rabbitmq:/var/log/rabbitmq
  restart: on-failure

psql:
  image: kobotoolbox/psql:latest
  # Dev: Build the image locally.
  # build: ./base_images/psql
  hostname: psql
  volumes:
    - ./.vols/db:/srv/db
  restart: on-failure

mongo:
  image: kobotoolbox/mongo:latest
  # Dev: Build the image locally.
  # build: ./base_images/mongo
  hostname: mongo
  environment:
    - MONGO_DATA=/srv/db
  # NOTE: On OS X and Windows, comment out the following `volumes` directive 
  #   as a workaround to a VirtualBox folder sharing+Mongo incompatibility.
  #   See the "WARNING" at https://hub.docker.com/_/mongo/
  volumes:
    - ./.vols/mongo:/srv/db
  restart: on-failure

kobocat:
  image: kobotoolbox/kobocat:latest
  # Dev: Build the image locally.
  # build: ../kobocat
  hostname: kobocat
  env_file:
    - ./envfile.server.txt
    - ./envfiles/smtp.txt
  links:
    - rabbit
    - mongo
    - psql
    - kpi
  volumes:
    - ./.vols/static/kobocat:/srv/static
    - ./scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash:ro
    - ./scripts/wait_for_mongo.bash:/etc/my_init.d/02_wait_for_mongo.bash:ro
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/03_wait_for_postgres.bash:ro
    - ./scripts/wait_for_kpi.bash:/etc/my_init.d/04_wait_for_kpi.bash:ro
    - ./scripts/computed_vars.server.source.bash:/etc/profile.d/kobocat_computed_vars.source.bash.sh:ro
    # Dev: Use the live `kobocat` directory from the host machine.
    # - ../kobocat:/srv/src/kobocat
    # Dev: Share your `.transifexrc` into the container.
    # - ./.transifexrc:/root/.transifexrc
  environment:
    - KOBOCAT_BROKER_URL=amqp://kobocat:kobocat@rabbit:5672/kobocat
    - ENKETO_PROTOCOL=https
    - ENKETO_VERSION=express
    - DJANGO_SETTINGS_MODULE=onadata.settings.kc_environ
    - DJANGO_DEBUG=False
    - DATABASE_URL=postgis://kobo:kobo@psql:5432/kobotoolbox
    - KOBO_PSQL_DB_NAME=kobotoolbox
    - KOBO_PSQL_DB_USER=kobo
  restart: on-failure
  # NOTE: Workaround to force name resolution inside containers. If enabled, 
  #   customize with your actual subdomains+domain and server IP. Clients 
  #   might also need similar manipulations to their `hosts` files.
  # extra_hosts:
  #   - 'kf-local.kobotoolbox.org:172.17.0.1'
  #   - 'ee-local.kobotoolbox.org:172.17.0.1'

kpi:
  image: kobotoolbox/kpi:latest
  # Dev: Build the image locally.
  # build: ../kpi
  hostname: kpi
  env_file:
    - ./envfile.server.txt
    - ./envfiles/smtp.txt
  links:
    - psql
    - rabbit
  volumes:
    - ./.vols/static/kpi:/srv/static
    # The Whoosh search index needs persistent storage
    - ./.vols/whoosh:/srv/whoosh
    - ./scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash:ro
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/02_wait_for_postgres.bash:ro
    - ./scripts/create_kobo_superuser.bash://etc/my_init.d/20_create_kobo_superuser.bash:ro
    - ./scripts/computed_vars.server.source.bash:/etc/profile.d/kpi_computed_vars.source.bash.sh:ro
    # Dev: Use the live `kpi` directory from the host machine.
    # - ../kpi:/srv/src/kpi
    # Dev: Share your `.transifexrc` into the container.
    # - ./.transifexrc:/root/.transifexrc
  environment:
    - ENKETO_VERSION=express
    - DATABASE_URL=postgres://kobo:kobo@psql:5432/kobotoolbox
    - DJANGO_DEBUG=False
    - KPI_PREFIX=/
  restart: on-failure
  # NOTE: Workaround to force name resolution inside containers. If enabled, 
  #   customize with your actual subdomains+domain and server IP. Clients 
  #   might also need similar manipulations to their `hosts` files.
  # extra_hosts:
  #   - 'kc-local.kobotoolbox.org:172.17.0.1'

nginx:
  image: kobotoolbox/nginx:latest
  # Dev: Build the image locally.
  # build: ./base_images/nginx
  hostname: nginx
  env_file:
    - ./envfile.server.txt
  environment:
    - NGINX_CONFIG_FILE_NAME=nginx_site_https.conf
    - NGINX_DEBUG_kpi=False
    - NGINX_DEBUG_kobocat=False
    - TEMPLATED_VAR_REFS=$${PUBLIC_DOMAIN_NAME} $${KOBOFORM_PUBLIC_SUBDOMAIN} $${KOBOCAT_PUBLIC_SUBDOMAIN} $${ENKETO_EXPRESS_PUBLIC_SUBDOMAIN}
  ports:
    - 80:80
    - 443:443
  volumes:
      - ./.vols/static:/srv/www:ro
      # get the logs out of glusterfs!
      - ./log/nginx:/var/log/nginx
      - ./nginx/:/tmp/kobo_nginx/:ro
      - ./nginx/nginx_command.bash:/etc/service/nginx/run:ro
      - ./secrets/:/tmp/kobo_toolbox_secrets/:ro
  links:
    - kobocat
    - kpi
    - enketo_express
  restart: on-failure

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
enketo_express:
  image: kobotoolbox/enketo_express
  # Dev: Build the image locally.
  # build: ../enketo-express/
  env_file:
    - ./envfile.server.txt
  links:
    - redis_main
    - redis_cache
  restart: on-failure
  volumes:
    - ./scripts/computed_vars.server.source.bash:/etc/profile.d/enketo_express_computed_vars.source.bash.sh:ro
    - ./enketo_express/config.json:/srv/tmp/enketo_express_config.json:ro
    - ./scripts/enketo_express_copy_config.bash:/etc/my_init.d/01_enketo_express_copy_config.bash:ro
    # Override Enketo Express icons.
    # - ./enketo_express/favicon.ico:/srv/src/enketo_express/public/images/favicon.ico:ro
    # - ./enketo_express/icon_180x180.png:/srv/src/enketo_express/public/images/icon_180x180.png:ro
    # Dev: Use the live `enketo-express` directory from the host machine.
    # - ../enketo-express:/srv/src/enketo_express
  # NOTE: Workaround to force name resolution inside containers. If enabled, 
  #   customize with your actual subdomains+domain and server IP. Clients 
  #   might also need similar manipulations to their `hosts` files.
  # extra_hosts:
  #   - 'kf-local.kobotoolbox.org:172.17.0.1'
  #   - 'kc-local.kobotoolbox.org:172.17.0.1'

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-main.conf:/etc/redis/redis.conf:ro
    - ./.vols/redis_main_data/:/data/
  restart: on-failure

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-cache.conf:/etc/redis/redis.conf:ro
  restart: on-failure
