# For public, HTTPS servers.
version: '2.2'

services:
  postgres:
    extends:
      file: docker-compose.backend.template.yml
      service: postgres
    environment:
      - KOBO_POSTGRES_DB_SERVER_ROLE=master

  mongo:
    extends:
      file: docker-compose.backend.template.yml
      service: mongo

  redis_main:
    extends:
      file: docker-compose.backend.template.yml
      service: redis_main
    environment:
      - KOBO_REDIS_SERVER_ROLE=main

  redis_cache:
    extends:
      file: docker-compose.backend.template.yml
      service: redis_cache
    environment:
      - KOBO_REDIS_SERVER_ROLE=cache
