# Back-end containers template.
# The primary and secondary compose files extend this file

version: '2.2'

services:
  postgres:
    image: postgis/postgis:14-3.2
    hostname: postgres
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/aws.txt
    volumes:
      - ./.vols/db:/var/lib/postgresql/data
      - ./backups/postgres:/srv/backups
      - ./log/postgres:/srv/logs
      - ./postgres:/kobo-docker-scripts
    command: "bash /kobo-docker-scripts/entrypoint.sh"
    restart: always
    stop_grace_period: 5m

  mongo:
    image: mongo:5.0
    hostname: mongo
    environment:
      - MONGO_DATA=/data/db
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/aws.txt
    volumes:
      - ./.vols/mongo:/data/db
      - ./backups/mongo:/srv/backups
      - ./mongo:/kobo-docker-scripts
      - ./log/mongo:/srv/logs
    restart: always
    command: "bash /kobo-docker-scripts/entrypoint.sh"
    stop_grace_period: 5m

  redis_main:
    image: redis:6.2
    env_file:
      - ../kobo-env/envfile.txt
      - ../kobo-env/envfiles/databases.txt
      - ../kobo-env/envfiles/aws.txt
    environment:
      - KOBO_REDIS_SERVER_ROLE=main
    volumes:
      - ./redis:/kobo-docker-scripts
      - ./backups/redis:/srv/backups
      - ./.vols/redis_main_data/:/data/
      - ./redis/redis-enketo-main.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_main:/var/log/redis
    restart: always
    stop_grace_period: 2m30s
    sysctls:
        - net.core.somaxconn=2048
    command: "bash /tmp/redis/entrypoint.sh"

  redis_cache:
    image: redis:6.2
    env_file:
      - ../kobo-env/envfiles/databases.txt
    environment:
      - KOBO_REDIS_SERVER_ROLE=cache
    volumes:
      - ./.vols/redis_cache_data/:/data/
      - ./redis/redis-enketo-cache.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_cache:/var/log/redis
    restart: always
    stop_grace_period: 2m30s
    sysctls:
        - net.core.somaxconn=2048
    command: "bash /tmp/redis/entrypoint.sh"
