rabbit:
  image: kobotoolbox/rabbit:latest
  # build: ./base_images/rabbit
  hostname: rabbit
  environment:
    - RABBITMQ_LOGS=-
    - RABBITMQ_SASL_LOGS=-
  restart: always

psql:
  image: kobotoolbox/psql:latest
  # build: ./base_images/psql
  hostname: psql
  volumes:
    - "./.vols/db:/srv/db"
  restart: always

mongo:
  image: kobotoolbox/mongo:latest
  # build: ./base_images/mongo
  hostname: mongo
  environment:
    - MONGO_DATA=/srv/db
  volumes:
    - "./.vols/mongo:/srv/db"
  restart: always

kobocat:
  image: kobotoolbox/kobocat:latest
  # build: ../kobocat
  hostname: kobocat
  env_file:
    - ./envfile.local.txt
  links:
    - rabbit
    - mongo
    - psql
  volumes:
    - "./.vols/static/kobocat:/srv/static"
    - ./scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash
    - ./scripts/wait_for_mongo.bash:/etc/my_init.d/02_wait_for_mongo.bash
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/03_wait_for_postgres.bash
    - ./scripts/computed_vars.local.source.bash:/etc/profile.d/kobocat_computed_vars.source.bash.sh:ro
  environment:
    - KOBOCAT_BROKER_URL=amqp://guest:guest@rabbit:5672/
    - ENKETO_PROTOCOL=http
    - ENKETO_VERSION=express
    - DJANGO_SETTINGS_MODULE=onadata.settings.kc_environ
    - DJANGO_DEBUG=False
    - DATABASE_URL=postgis://kobo:kobo@psql:5432/kobotoolbox
    - KOBO_PSQL_DB_NAME=kobotoolbox
    - KOBO_PSQL_DB_USER=kobo
    #- KOBOCAT_TEMPLATES_PATH=/srv/src/kobocat-template
  restart: always

kpi:
  image: kobotoolbox/kpi:latest
  # build: ../kpi
  hostname: kpi
  env_file:
    - ./envfile.local.txt
  links:
    - psql
    - rabbit
  volumes:
    - "./.vols/static/kpi:/srv/static"
    # The Whoosh search index needs persistent storage
    - "./.vols/whoosh:/srv/whoosh"
    - ./scripts/wait_for_rabbit.bash:/etc/my_init.d/01_wait_for_rabbit.bash
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/02_wait_for_postgres.bash
    - ./scripts/computed_vars.local.source.bash:/etc/profile.d/kpi_computed_vars.source.bash.sh:ro
  environment:
    - ENKETO_VERSION=express
    - DATABASE_URL=postgres://kobo:kobo@psql:5432/kobotoolbox
    - DJANGO_DEBUG=False
    - KPI_PREFIX=/
  restart: always

nginx:
  image: kobotoolbox/nginx:latest
  # build: ./base_images/nginx
  hostname: nginx
  env_file:
    - ./envfile.local.txt
  environment:
    - NGINX_CONFIG_FILE_NAME=nginx_site_http.conf
    - NGINX_DEBUG_kpi=False
    - NGINX_DEBUG_dkobo=False
    - NGINX_DEBUG_kobocat=False
    - TEMPLATED_VAR_REFS=$${KOBOCAT_PUBLIC_PORT} $${KOBOFORM_PUBLIC_PORT} $${KPI_PUBLIC_PORT} $${ENKETO_EXPRESS_PUBLIC_PORT}
  ports:
    - 8000:8000
    - 8001:8001
    - 8002:8002
    - 8005:8005
  volumes:
      - "./.vols/static:/srv/www:ro"
      # get the logs out of glusterfs!
      - "./.vols/../log/nginx:/var/log/nginx"
      - ./nginx/:/tmp/kobo_nginx/:ro
      - ./nginx/nginx_command.bash:/etc/service/nginx/run:ro
  links:
    - kobocat
    - dkobo
    - kpi
    - enketo_express
  restart: always

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
enketo_express:
  image: kobotoolbox/enketo_express
  # build: ../enketo-express/
  env_file:
    - ./envfile.local.txt
  links:
    - redis_main
    - redis_cache
  restart: always

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_main:
  image: redis:2.6
  # Map our "main" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-main.conf:/etc/redis/redis.conf
    - "./.vols/redis_main_data/:/data/"
  restart: always

# Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
redis_cache:
  image: redis:2.6
  # Map our "cache" Redis config into the container.
  volumes:
    - ./redis/redis-enketo-cache.conf:/etc/redis/redis.conf
  restart: always

dkobo:
  image: kobotoolbox/dkobo:latest
  # build: ../dkobo
  hostname: dkobo
  env_file:
    - ./envfile.local.txt
  links:
    - psql
  volumes:
    - "./.vols/static/koboform:/srv/static"
    - ./scripts/wait_for_postgres.bash:/etc/my_init.d/01_wait_for_postgres.bash
    - ./scripts/computed_vars.local.source.bash:/etc/profile.d/dkobo_computed_vars.source.bash.sh:ro
    - ./scripts/dkobo_command.bash:/tmp/dkobo_command.bash:ro
  environment:
    - ENKETO_VERSION=express
    - DATABASE_URL=postgres://kobo:kobo@psql:5432/kobotoolbox
    - DJANGO_SETTINGS_MODULE=dkobo.settings
    - DJANGO_DEBUG=False
  restart: always
  command: bash /tmp/dkobo_command.bash
