# For public, HTTPS servers.
version: '2.1'

services:
  rabbit:
    image: kobotoolbox/rabbit:latest
    hostname: rabbit
    environment:
      - RABBITMQ_LOG_BASE=/var/log/rabbitmq
    volumes:
      - ./log/rabbitmq:/var/log/rabbitmq
    restart: on-failure
    ports:
      - 5672:5672

  postgres:
    #image: mdillon/postgis:9.5
    image: kobojohn/postgis:9.4
    hostname: postgres
    env_file:
      - ../kobo-deployments/envfile.txt
      - ../kobo-deployments/envfiles/databases.txt
    volumes:
      - ./.vols/db:/var/lib/postgresql/data
      - ./backups/postgres:/srv/backups
      - ./log/postgres:/srv/logs
      - ./postgres:/kobo-docker-scripts
    command: "/bin/bash /kobo-docker-scripts/entrypoint.sh"
    restart: on-failure
    ports:
      - 5432:5432

  mongo:
    image: mongo:3.4
    hostname: mongo
    environment:
      - MONGO_DATA=/data/db
    env_file:
      - ../kobo-deployments/envfile.txt
      - ../kobo-deployments/envfiles/databases.txt
    volumes:
      - ./.vols/mongo:/data/db
      - ./backups/mongo:/srv/backups
      - ./base_images/mongo/run_mongo:/etc/service/mongo/run
    restart: on-failure
    ports:
      - 27017:27017

  # Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
  redis_main:
    image: redis:3.2
    # Map our "main" Redis config into the container.
    volumes:
      - ./.vols/redis_main_data/:/data/
      - ./redis/redis-enketo-main.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_main:/var/log/redis
    restart: on-failure
    ports:
      - 6379:6379
    sysctls:
        - net.core.somaxconn=2048

    command: "/bin/bash /tmp/redis/entrypoint.sh"

  # Adapted from https://github.com/kobotoolbox/enketo-express/blob/docker/docker-compose.yml.
  redis_cache:
    image: redis:3.2
    # Map our "cache" Redis config into the container.
    volumes:
      - ./redis/redis-enketo-cache.conf.tmpl:/etc/redis/redis.conf.tmpl:ro
      - ./redis/entrypoint.sh:/tmp/redis/entrypoint.sh:ro
      - ./log/redis_cache:/var/log/redis
    restart: on-failure
    ports:
      - 6380:6380
    sysctls:
        - net.core.somaxconn=2048

    command: "/bin/bash /tmp/redis/entrypoint.sh"
